version: 2.1
jobs:
  Before-Install:
    docker:
      - image: cimg/openjdk:11.0.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Pull openjdk11
          command: |
            echo 'My dockerhub username is:'
            echo $DOCKERHUB_USERNAME
  Run-Script:
    docker:
      - image: cimg/openjdk:11.0.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Running maven script
          command: |
            chmod +x ./mvnw
            ./mvnw clean install
            ./mvnw deploy jib:build -Djib.to.auth.username=$DOCKERHUB_USERNAME -Djib.to.auth.password=$DOCKERHUB_PASSWORD -P deploy-docker
workflows:
  Spring-Boot-Workflow:
    jobs:
      - Before-Install
      - Run-Script:
          requires:
            - Before-Install