version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.3
jobs:
  Before-Install:
    docker:
      - image: cimg/openjdk:11.0.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Pull openjdk11
          command: |
            echo 'My dockerhub username is:'
            echo $DOCKERHUB_USERNAME
  Run-Script:
    docker:
      - image: cimg/openjdk:11.0.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Running maven script
          command: |
            chmod +x ./mvnw
            ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install
            ./mvnw deploy jib:build -Djib.to.auth.username=$DOCKERHUB_USERNAME -Djib.to.auth.password=$DOCKERHUB_PASSWORD -P deploy-docker
  Send-Tests-Report:
    docker:
      - image: cimg/openjdk:11.0.11-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Sending tests report
          command:
            mvn test
      - store_artifacts:
          path: target
workflows:
  Spring-Boot-Workflow:
    jobs:
      - Before-Install
      - Run-Script:
          requires:
            - Before-Install
      - Send-Tests-Report:
          requires:
            - Run-Script